### ISSUE TITLE
FYI - adding how2sign to sign-language-datasets

### ISSUE THREAD

**Issue by AmitMY** [how2sign/how2sign-data#1]
Just writing to let you know I've added how2sign to [sign-language-datasets](https://github.com/sign-language-processing/datasets), in order to prevent double-work.

It is in the master branch: https://github.com/sign-language-processing/datasets/blob/master/sign_language_datasets/datasets/how2sign/how2sign.py

**Looking forward for the English translation to be available, as well as the side poses, and 3D poses.**

To load the dataset one just needs to:
```python
config = SignDatasetConfig(name="only-annotations", version="1.0.0", include_video=False, include_pose=None)
how2sign = tfds.load(name='how2sign', builder_kwargs=dict(config=config))

for datum in how2sign["train"]:
  print(datum['id'].numpy().decode('utf-8'))
```

With the config, one can choose to download the videos or not, and poses or not, as well as modify the video resolution/fps for a smaller dataset size and faster loading:
```python
SignDatasetConfig(name="videos_and_poses256x256:12", 
                           version="3.0.0",          # Specific version
                           include_video=True,       # Download and load dataset videos
                           process_video=True,       # Process videos to tensors, or only save path to video
                           fps=12,                   # Load videos at constant, 12 fps
                           resolution=(256, 256),    # Convert videos to a constant resolution, 256x256
                           include_pose="openpose")  # Download and load OpenPose pose estimation
```

**Comment by how2sign** [comment]
Thank you so much, Amit for your great work! 
We would like to let you know that the re-aligned English sentences are already available in case you would like to add them to your repo.


Thank you,
